---
functional:
  - Возможность регистрации игрока
  - Возможность авторизации
  - Создание игры для соревнования
  - Возможность соревноваться друг с другом в решении задач
  - Выполнение задачи на разных языках программирования
  - Возможность смены языка программирования во время решения
  - Возможность временного контроля выполнения задачи для определения победителя
  - Возможность видеть написание кода друг у друга при соревновании
  - Возможность начисления очков для рейтинга
  - Ведение рейтинга за неделю, за месяц и за все время и возможность его просматривать
  - Возможность игры с ботом
  - Игра с другом по ссылке
  - Наличие нескольких уровней сложности игры- elementary, easy, medium, hard
  - Возможность выбора игры
  - При нежелании выбора игры пользователем, должен происходить случайный выбор игры
  - Задачи даются на  русском и английском языках
  - Возможность просматривать и следить за игрой посторонним пользователям
  - Наличие чата для общения зарегистрированных пользователей
  - Возможность просматривать уже завершенные игры
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика, больше 1000 одновременных пользователей
  - Редактор для ввода кода должен выглядеть как проигрыватель
implicit:
  - Открытый исходный код
